### ISSUE TITLE
Criar fluxograma: upload de arquivo

### ISSUE THREAD

**Issue by ghost** [roicenir/TCC2#3]
Criar um diagrama, no TCC, explicando como funciona o upload de um arquivo no servidor HTTPS, para que aquele seja disponibilizado como *link* magnético.

Depende de #2.

**Comment by roicenir** [comment]
Primeiramente, o cliente acessa a aplicação web. Então, aparecerá um botão para escolher o caminho do arquivo a ser adicionado no servidor, o qual deverá encontrar-se no dispositivo do cliente. Após informado qual arquivo deve ser inserido, o cliente deve clicar no botão “Enviar Arquivo”. Isso ocorrendo, uma requisição será enviada para o servidor de arquivos, passando o arquivo como parâmetro da requisição. Um código javascript estará rodando no servidor de arquivos, onde o mesmo tem um processo aberto na porta 8080, que ficará aguardando receber um arquivo. Recebida a requisição, a aplicação irá adicionar o arquivo no servidor de arquivos web. O resultado da operação será informado ao usuário.

![upload](https://user-images.githubusercontent.com/22074879/102997267-6ebc8880-4503-11eb-9e45-9fbe70e80323.png)
