### ISSUE TITLE
Criar diagrama: download de arquivo

### ISSUE THREAD

**Issue by ghost** [roicenir/TCC2#4]
Uma vez que o arquivo já está disponível tanto por HTTPS quanto pela rede P2P, conforme #3, criar um diagrama explicando como o jogador/cliente baixa o arquivo com 0, 1 ou 2+ *seeders* P2P.

Depende de #2 e #3.

**Comment by roicenir** [comment]
Para o download de um arquivo, o usuário deverá informar o link magnético do arquivo que deseja fazer o download. Então, o servidor de arquivos irá executar o Instant.io, que é um código que contém um Streaming de transferência de arquivo sobre WebTorrent. Ele utiliza o WebRTC para localizar os seeders que contém os blocos do arquivo desejado, e então, a transferência ocorre bloco por bloco, par a par, entre o cliente e os seeders. Em tempo real, o Instant.io notifica o cliente com informações sobre o download, como o número de peers disponíveis para aquele arquivo, o percentual de progresso do arquivo, a velocidade de download e upload do usuário e o tempo restante estimado para conclusão do download.  

![Download](https://user-images.githubusercontent.com/22074879/102997337-9c093680-4503-11eb-9589-6c4109314dc1.png)
